apiVersion: apps/v1
kind: Deployment
metadata:
  name: flippy
  labels:
    app: flippy-webapi
spec:
  replicas: 1
  selector:
    matchLabels:
      service: flippy
  template:
    metadata:
      labels:
        app: flippy-webapi
        service: flippy
    spec:
      containers:
        - name: flippy
          image: exploredocker.azurecr.io/flippy:v1
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 80
              protocol: TCP
          env:
            - name: ASPNETCORE_URLS
              value: http://+:80
---
apiVersion: v1
kind: Service
metadata:
  name: flippy
  labels:
    app: flippy-webapi
    service: flippy
spec:
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
  selector:
    service: flippy

